In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [3]:
note_seq[0:5], note_seq[1:6]

(['g8', 'e8', 'e4', 'f8', 'd8'], ['e8', 'e4', 'f8', 'd8', 'd4'])

# Data preprocessing

In [4]:
dataset = list()
for i in range(len(note_seq)-5):
  subset = note_seq[i:i+5]  
  items  = list()

  for item in subset:
    items.append(code2idx[item])  # item은 key값, code2index[item]는 value값(숫자)
  
  dataset.append(items)
print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9]]


In [5]:
import numpy as np

datasets = np.array(dataset)

In [6]:
x_train = datasets[:, 0:4] 
x_train.shape

(49, 4)

In [7]:
y_train =  datasets[:,4] 
y_train.shape

(49,)

In [8]:
x_train = x_train / 13
x_train[3]

array([0.76923077, 0.61538462, 0.07692308, 0.53846154])

# Make model

In [9]:
import tensorflow as tf

In [10]:
x_train.shape 
x_train[2]

array([0.15384615, 0.76923077, 0.61538462, 0.07692308])

In [11]:
x_train = np.reshape(x_train, (49, 4, 1))
x_train.shape, x_train[2]

((49, 4, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462],
        [0.07692308]]))

In [12]:
np.unique(y_train) 

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

# Training

In [13]:
model = tf.keras.Sequential()

# Input Layer 
model.add(tf.keras.layers.Input(shape=(4,1)))

# Hidden Layer
model.add(tf.keras.layers.LSTM(128))

# Output Layer
model.add(tf.keras.layers.Dense(13, activation='softmax'))

# Gadget
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [14]:
hist = model.fit(x_train, y_train, epochs=1000, batch_size=5)

# batch_size= 5 -> step size= 50/5= 10 

Epoch 1/1000
10/10 [==============================] - 2s 4ms/step - loss: 2.5221 - accuracy: 0.2857 
Epoch 2/1000
10/10 [==============================] - 0s 4ms/step - loss: 2.4090 - accuracy: 0.3469
Epoch 3/1000
10/10 [==============================] - 0s 4ms/step - loss: 2.2639 - accuracy: 0.3469
Epoch 4/1000
10/10 [==============================] - 0s 4ms/step - loss: 2.0842 - accuracy: 0.3469
Epoch 5/1000
10/10 [==============================] - 0s 5ms/step - loss: 1.9952 - accuracy: 0.3469
Epoch 6/1000
10/10 [==============================] - 0s 4ms/step - loss: 1.9442 - accuracy: 0.3469
Epoch 7/1000
10/10 [==============================] - 0s 4ms/step - loss: 1.9296 - accuracy: 0.3469
Epoch 8/1000
10/10 [==============================] - 0s 5ms/step - loss: 1.9196 - accuracy: 0.3469
Epoch 9/1000
10/10 [==============================] - 0s 4ms/step - loss: 1.9120 - accuracy: 0.3469
Epoch 10/1000
10/10 [==============================] - 0s 4ms/step - loss: 1.8996 - accuracy: 0.346

# Evaluation

In [15]:
model.evaluate(x_train, y_train)

2/2 [==============================] - 0s 7ms/step - loss: 0.3191 - accuracy: 0.8571


[0.31907886266708374, 0.8571428656578064]

In [16]:
pred = model.predict( x_train[0:1] )

In [17]:
np.argmax(pred)

8