In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [3]:
dataset = list()
for i in range(len(note_seq)-5):
  subset = note_seq[i:i+5]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item]) # item = key, value 값이 나옴
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9]]


In [4]:
import numpy as np
datasets = np.array(dataset)

In [5]:
x_train = datasets[:, 0:4]
x_train.shape # --> tensorflow tensor type(tensor) (50, 3, 1)

(49, 4)

In [23]:
x_train = x_train / 13
x_train[3]

array([0.00422654, 0.00338123, 0.00042265, 0.00295858])

In [24]:
X_train = np.reshape(x_train, (49, 4, 1))
X_train.shape, X_train[2]

((49, 4, 1), array([[0.00084531],
        [0.00422654],
        [0.00338123],
        [0.00042265]]))

In [25]:
y_train = datasets[:,4]
y_train.shape

(49,)

In [26]:
len(code2idx)

14

In [12]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

# make model

In [13]:
import tensorflow as tf

In [27]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(4,1)))  # input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(14, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [28]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10)  # 50 / 5 = 10

Epoch 1/500
5/5 [==============================] - 2s 7ms/step - loss: 2.6349 - accuracy: 0.1633
Epoch 2/500
5/5 [==============================] - 0s 7ms/step - loss: 2.6133 - accuracy: 0.3469
Epoch 3/500
5/5 [==============================] - 0s 6ms/step - loss: 2.5850 - accuracy: 0.3469
Epoch 4/500
5/5 [==============================] - 0s 7ms/step - loss: 2.5367 - accuracy: 0.3469
Epoch 5/500
5/5 [==============================] - 0s 7ms/step - loss: 2.4612 - accuracy: 0.3469
Epoch 6/500
5/5 [==============================] - 0s 6ms/step - loss: 2.3307 - accuracy: 0.3469
Epoch 7/500
5/5 [==============================] - 0s 8ms/step - loss: 2.1632 - accuracy: 0.3469
Epoch 8/500
5/5 [==============================] - 0s 6ms/step - loss: 2.0311 - accuracy: 0.3469
Epoch 9/500
5/5 [==============================] - 0s 9ms/step - loss: 1.9988 - accuracy: 0.3469
Epoch 10/500
5/5 [==============================] - 0s 7ms/step - loss: 1.9787 - accuracy: 0.3469
Epoch 11/500
5/5 [===========

In [29]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 7ms/step - loss: 1.8614 - accuracy: 0.3469


[1.8613661527633667, 0.3469387888908386]

In [30]:
X_train[4:5]

array([[[0.00338123],
        [0.00042265],
        [0.00295858],
        [0.00338123]]])

In [31]:
model.predict(X_train[4:5])

array([[2.4142391e-05, 6.0894631e-02, 4.0264018e-02, 2.0357171e-02,
        3.9592724e-02, 2.3300512e-05, 2.1355972e-05, 6.0942981e-02,
        1.8328093e-01, 3.4933245e-01, 8.3003715e-02, 1.6221170e-01,
        2.3576767e-05, 2.7302725e-05]], dtype=float32)

In [34]:
first = 0.00338123
second = 0.00042265
third = 0.00295858
fourth = 0.00338123

In [35]:
pred = model.predict([[[first],[second],[third],[fourth]]])

In [36]:
np.argmax(pred)

9