In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [3]:
dataset = list()
for i in range(len(note_seq)-5):
  subset = note_seq[i:i+5]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item]) # item = key, value 값이 나옴
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9]]


In [4]:
import numpy as np
datasets = np.array(dataset)

In [5]:
x_train = datasets[:, 0:4]
x_train.shape # --> tensorflow tensor type(tensor) (50, 3, 1)

(49, 4)

In [6]:
X_train = np.reshape(x_train, (49, 4, 1))
X_train.shape, X_train[2]

((49, 4, 1), array([[ 2],
        [10],
        [ 8],
        [ 1]]))

In [10]:
y_train = datasets[:,4]
y_train.shape

(49,)

In [9]:
len(code2idx)

14

In [11]:
x_train = x_train / 14
x_train[3]

array([0.71428571, 0.57142857, 0.07142857, 0.5       ])

In [12]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

# make model

In [13]:
import tensorflow as tf

In [14]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(4,1)))  # input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(14, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [15]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10)  # 50 / 5 = 10

Epoch 1/500
5/5 [==============================] - 2s 8ms/step - loss: 2.5423 - accuracy: 0.3061
Epoch 2/500
5/5 [==============================] - 0s 6ms/step - loss: 2.2361 - accuracy: 0.3469
Epoch 3/500
5/5 [==============================] - 0s 6ms/step - loss: 2.0948 - accuracy: 0.3469
Epoch 4/500
5/5 [==============================] - 0s 6ms/step - loss: 2.0057 - accuracy: 0.3469
Epoch 5/500
5/5 [==============================] - 0s 6ms/step - loss: 1.9676 - accuracy: 0.3469
Epoch 6/500
5/5 [==============================] - 0s 6ms/step - loss: 1.9274 - accuracy: 0.3469
Epoch 7/500
5/5 [==============================] - 0s 6ms/step - loss: 1.9115 - accuracy: 0.3469
Epoch 8/500
5/5 [==============================] - 0s 6ms/step - loss: 1.8892 - accuracy: 0.3469
Epoch 9/500
5/5 [==============================] - 0s 8ms/step - loss: 1.8711 - accuracy: 0.3469
Epoch 10/500
5/5 [==============================] - 0s 7ms/step - loss: 1.8600 - accuracy: 0.3469
Epoch 11/500
5/5 [===========

In [16]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 8ms/step - loss: 0.2801 - accuracy: 0.8980


[0.28007271885871887, 0.8979591727256775]

In [17]:
X_train[4:5]

array([[[8],
        [1],
        [7],
        [8]]])

In [18]:
model.predict(X_train[4:5])

array([[6.8769725e-05, 2.0825681e-03, 6.1724968e-05, 1.5392953e-03,
        2.6003430e-05, 1.2112068e-04, 1.7278489e-04, 1.0767587e-03,
        7.6189018e-03, 4.0726262e-01, 1.6206347e-04, 5.7954782e-01,
        1.3735416e-04, 1.2218268e-04]], dtype=float32)

In [19]:
first = 0.04733728
second = 0.00591716
third = 0.04142012

In [20]:
pred = model.predict([[[first],[second],[third]]])

In [21]:
np.argmax(pred)

7