<a href="https://colab.research.google.com/github/SanghunOh/exec_bigdataservice/blob/main/Notescale/Notescale_LSTM_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
note_seq[0:5], note_seq[1:6], note_seq[2:7]

(['g8', 'e8', 'e4', 'f8', 'd8'],
 ['e8', 'e4', 'f8', 'd8', 'd4'],
 ['e4', 'f8', 'd8', 'd4', 'c8'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [5]:
len(note_seq), range(len(note_seq)-5)

(54, range(0, 49))

In [9]:
dataset = list()
for i in range(len(note_seq)-4):
  # print(note_seq[i:i+5])
  subset = note_seq[i:i+5]
  items = list()
  for item in subset:
    code2idx[item]
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)
print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2]]


In [10]:
import numpy as np
datasets = np.array(dataset)

In [16]:
x_train = datasets[:,:4]
x_train.shape, x_train

((50, 4), array([[11,  9,  2, 10],
        [ 9,  2, 10,  8],
        [ 2, 10,  8,  1],
        [10,  8,  1,  7],
        [ 8,  1,  7,  8],
        [ 1,  7,  8,  9],
        [ 7,  8,  9, 10],
        [ 8,  9, 10, 11],
        [ 9, 10, 11, 11],
        [10, 11, 11,  4],
        [11, 11,  4, 11],
        [11,  4, 11,  9],
        [ 4, 11,  9,  9],
        [11,  9,  9,  9],
        [ 9,  9,  9, 10],
        [ 9,  9, 10,  8],
        [ 9, 10,  8,  1],
        [10,  8,  1,  7],
        [ 8,  1,  7,  9],
        [ 1,  7,  9, 11],
        [ 7,  9, 11, 11],
        [ 9, 11, 11,  9],
        [11, 11,  9,  9],
        [11,  9,  9,  2],
        [ 9,  9,  2,  8],
        [ 9,  2,  8,  8],
        [ 2,  8,  8,  8],
        [ 8,  8,  8,  8],
        [ 8,  8,  8,  8],
        [ 8,  8,  8,  9],
        [ 8,  8,  9,  3],
        [ 8,  9,  3,  9],
        [ 9,  3,  9,  9],
        [ 3,  9,  9,  9],
        [ 9,  9,  9,  9],
        [ 9,  9,  9,  9],
        [ 9,  9,  9, 10],
        [ 9,  9, 10,  4],
   

In [15]:
y_train = datasets[:,4]
y_train.shape, y_train

((50,),
 array([ 8,  1,  7,  8,  9, 10, 11, 11,  4, 11,  9,  9,  9, 10,  8,  1,  7,
         9, 11, 11,  9,  9,  2,  8,  8,  8,  8,  8,  9,  3,  9,  9,  9,  9,
         9, 10,  4, 11,  9,  2, 10,  8,  1,  7,  9, 11, 11,  9,  9,  2]))

In [17]:
x_train = x_train / 13
x_train[2] 

array([0.15384615, 0.76923077, 0.61538462, 0.07692308])

In [19]:
X_train = np.reshape(x_train, (50, 4, 1))
X_train.shape, X_train[2]

((50, 4, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462],
        [0.07692308]]))

In [18]:
import tensorflow as tf

In [20]:
model = tf.keras.models.Sequential()

In [21]:
model.add(tf.keras.Input(shape=(4, 1)))
model.add(tf.keras.layers.LSTM(128))
model.add(tf.keras.layers.Dense(14, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc'])

In [22]:
model.fit(X_train, y_train, epochs=1000, batch_size=10)

Epoch 1/1000
5/5 [==============================] - 2s 6ms/step - loss: 2.6232 - acc: 0.1600
Epoch 2/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.5671 - acc: 0.3400
Epoch 3/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.5027 - acc: 0.3400
Epoch 4/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.4362 - acc: 0.3400
Epoch 5/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.3457 - acc: 0.3400
Epoch 6/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.2304 - acc: 0.3400
Epoch 7/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.1060 - acc: 0.3400
Epoch 8/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.0353 - acc: 0.3400
Epoch 9/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.0001 - acc: 0.3400
Epoch 10/1000
5/5 [==============================] - 0s 5ms/step - loss: 1.9785 - acc: 0.3400
Epoch 11/1000
5/5 [==============================] - 0s 5ms/step - lo

# evaluation

In [23]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 7ms/step - loss: 0.4110 - acc: 0.8600


[0.41099220514297485, 0.8600000143051147]

In [24]:
X_train[0:1]

array([[[0.84615385],
        [0.69230769],
        [0.15384615],
        [0.76923077]]])

In [26]:
pred = model.predict(X_train[0:1])

In [27]:
np.argmax(pred)

8

In [28]:
pred1 = model.predict(X_train[1:2])

In [29]:
np.argmax(pred1)

1

In [30]:
pred2 = model.predict(X_train[2:3])

In [32]:
np.argmax(pred2)

7