In [72]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [73]:
note_seq[0:5]

['g8', 'e8', 'e4', 'f8', 'd8']

In [74]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [75]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [76]:
len(note_seq), range(len(note_seq)-5) # [4,8,12,....]

(54, range(0, 49))

In [77]:
code2idx['g8']

11

In [78]:
dataset = list()
for i in range(len(note_seq)-5):
  subset = note_seq[i:i+5]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9]]


In [79]:
import numpy as np
datasets = np.array(dataset)

In [80]:
x_train = datasets[:,0:4]
x_train.shape, #x_train

((49, 4),)

In [81]:
y_train = datasets[:,4]
y_train.shape, #y_train

((49,),)

In [51]:
len(code2idx)

14

In [82]:
x_train = x_train / 14 # len(code2idx)
x_train[4]

array([0.57142857, 0.07142857, 0.5       , 0.57142857])

# make model

In [53]:
import tensorflow as tf

In [83]:
x_train.shape, x_train[4] # --> scale

((49, 4), array([0.57142857, 0.07142857, 0.5       , 0.57142857]))

In [84]:
X_train = np.reshape(x_train, (49, 4, 1)) # tensor
X_train.shape, X_train[2]

((49, 4, 1), array([[0.14285714],
        [0.71428571],
        [0.57142857],
        [0.07142857]]))

In [85]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [86]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(4,1))) # input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(14, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [ ]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=10) # 50 / 5 = 10

In [88]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 8ms/step - loss: 0.9291 - accuracy: 0.6531


[0.9291333556175232, 0.6530612111091614]

In [89]:
X_train[4:5]

array([[[0.57142857],
        [0.07142857],
        [0.5       ],
        [0.57142857]]])

In [90]:
model.predict(X_train[4:5])

array([[2.68675903e-05, 2.36940868e-02, 6.97129231e-04, 3.58562986e-03,
        3.05090565e-04, 7.54212851e-06, 1.48208765e-05, 5.06614379e-06,
        4.57970761e-02, 2.67819047e-01, 1.17948977e-03, 6.56851053e-01,
        1.07155702e-05, 6.44758120e-06]], dtype=float32)

In [62]:
first = 0.61538462
second = 0.07692308
third = 0.53846154

In [91]:
pred = model.predict(X_train[0:1])

In [92]:
np.argmax(pred)

8

In [65]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [66]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']