<a href="https://colab.research.google.com/github/SanghunOh/exec_bigdataservice/blob/main/Notescale/NoteScale_LSTM12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [ ]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [ ]:

dataset = list()
for i in range(len(note_seq)-5):
  subset = note_seq[i:i+5]
  items = list()
  for item in subset:
     items.append(code2idx[item])
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9]]


In [ ]:
import numpy as np
datasets = np.array(dataset)

In [ ]:
x_train = datasets[:, 0:4]
x_train.shape 

(49, 4)

In [ ]:
X_train = np.reshape(x_train, (49, 4, 1))
X_train.shape, X_train[2]

((49, 4, 1), array([[ 2],
        [10],
        [ 8],
        [ 1]]))

In [ ]:
y_train = datasets[:,4]
y_train.shape

(49,)

In [ ]:
len(code2idx)

14

In [ ]:
x_train = x_train / 14
x_train[3]

array([0.71428571, 0.57142857, 0.07142857, 0.5       ])

In [ ]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

# make model

In [ ]:
import tensorflow as tf

In [ ]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(4,1))) 
model.add(tf.keras.layers.LSTM(128))
model.add(tf.keras.layers.Dense(14, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [ ]:
hist = model.fit(X_train, y_train, epochs=2000, batch_size=10) 

Epoch 1/2000
5/5 [==============================] - 2s 9ms/step - loss: 2.4987 - accuracy: 0.2041
Epoch 2/2000
5/5 [==============================] - 0s 7ms/step - loss: 2.2150 - accuracy: 0.3061
Epoch 3/2000
5/5 [==============================] - 0s 8ms/step - loss: 2.0405 - accuracy: 0.3469
Epoch 4/2000
5/5 [==============================] - 0s 8ms/step - loss: 1.9788 - accuracy: 0.3469
Epoch 5/2000
5/5 [==============================] - 0s 8ms/step - loss: 1.9323 - accuracy: 0.3469
Epoch 6/2000
5/5 [==============================] - 0s 8ms/step - loss: 1.8996 - accuracy: 0.3469
Epoch 7/2000
5/5 [==============================] - 0s 7ms/step - loss: 1.8847 - accuracy: 0.3469
Epoch 8/2000
5/5 [==============================] - 0s 7ms/step - loss: 1.8707 - accuracy: 0.3469
Epoch 9/2000
5/5 [==============================] - 0s 11ms/step - loss: 1.8546 - accuracy: 0.3469
Epoch 10/2000
5/5 [==============================] - 0s 8ms/step - loss: 1.8432 - accuracy: 0.3469
Epoch 11/2000
5/5 

In [ ]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 1s 10ms/step - loss: 0.1351 - accuracy: 0.9184


[0.13507263362407684, 0.918367326259613]

In [ ]:
X_train[4:5]

array([[[8],
        [1],
        [7],
        [8]]])

In [ ]:
model.predict(X_train[4:5])

array([[1.2422502e-06, 6.3928401e-06, 7.0946993e-07, 7.5327134e-06,
        1.5234106e-06, 2.9763055e-06, 1.9880506e-06, 2.7344237e-05,
        1.2516156e-03, 9.8864275e-01, 6.5926921e-05, 9.9847130e-03,
        2.6021912e-06, 2.7462791e-06]], dtype=float32)

In [ ]:
first = 0.04733728
second = 0.00591716
third = 0.04142012

In [ ]:
pred = model.predict([[[first],[second],[third]]])

In [ ]:
np.argmax(pred)

7