<a href="https://colab.research.google.com/github/SanghunOh/exec_bigdataservice/blob/main/Notescale/Notescale_LSTM_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 악보 LSTM

x size : 4 ,y_size : 1

predict

plot(y_true, y_pred)

## 데이터 전처리

1차원 -> 2차원으로 변경

In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
note_seq[0:5], note_seq[1:6], note_seq[2:7]

(['g8', 'e8', 'e4', 'f8', 'd8'],
 ['e8', 'e4', 'f8', 'd8', 'd4'],
 ['e4', 'f8', 'd8', 'd4', 'c8'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [4]:
len(note_seq), range(len(note_seq)-5)

(54, range(0, 49))

In [5]:
dataset = list()
for i in range(len(note_seq)-5):
  subset = note_seq[i:i+5]
  items = list()
  for item in subset:
     items.append(code2idx[item])
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9]]


In [6]:
import numpy as np

In [7]:
datasets = np.array(dataset)

In [8]:
x_train = datasets[:,0:4]
x_train.shape

(49, 4)

In [9]:
y_train = datasets[:,3]
y_train.shape

(49,)

In [10]:
len(code2idx)

14

In [11]:
x_train = x_train/14
x_train[3]

array([0.71428571, 0.57142857, 0.07142857, 0.5       ])

In [12]:
X_train = np.reshape(x_train, (49, 4, 1))
X_train.shape, X_train[2]

((49, 4, 1), array([[0.14285714],
        [0.71428571],
        [0.57142857],
        [0.07142857]]))

In [13]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [14]:
import tensorflow as tf

In [15]:
model = tf.keras.models.Sequential()

In [16]:
model.add(tf.keras.Input(shape=(4,1))) 
model.add(tf.keras.layers.LSTM(128)) 
model.add(tf.keras.layers.Dense(13, activation='softmax')) 

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [17]:
hist = model.fit(X_train, y_train, epochs=1000, batch_size=10)

Epoch 1/1000
5/5 [==============================] - 2s 9ms/step - loss: 2.5503 - accuracy: 0.0816
Epoch 2/1000
5/5 [==============================] - 0s 7ms/step - loss: 2.4956 - accuracy: 0.3265
Epoch 3/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.4467 - accuracy: 0.3265
Epoch 4/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.3855 - accuracy: 0.3265
Epoch 5/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.3012 - accuracy: 0.3265
Epoch 6/1000
5/5 [==============================] - 0s 7ms/step - loss: 2.2111 - accuracy: 0.3265
Epoch 7/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.1030 - accuracy: 0.3265
Epoch 8/1000
5/5 [==============================] - 0s 9ms/step - loss: 2.0089 - accuracy: 0.3265
Epoch 9/1000
5/5 [==============================] - 0s 6ms/step - loss: 1.9854 - accuracy: 0.3265
Epoch 10/1000
5/5 [==============================] - 0s 6ms/step - loss: 1.9733 - accuracy: 0.3265
Epoch 11/1000
5/5 [

In [18]:
model.evaluate(X_train,y_train)

2/2 [==============================] - 0s 8ms/step - loss: 0.1357 - accuracy: 0.9796


[0.13566680252552032, 0.9795918464660645]

In [19]:
X_train[2:3]

array([[[0.14285714],
        [0.71428571],
        [0.57142857],
        [0.07142857]]])

In [20]:
model.predict(X_train[2:3])

array([[4.9002469e-10, 9.9185842e-01, 3.7969258e-03, 1.2269233e-03,
        7.7795667e-05, 1.1238684e-09, 5.4164701e-10, 9.3691703e-08,
        3.0172754e-03, 2.2668153e-05, 9.0324435e-11, 1.6350496e-14,
        1.0425076e-09]], dtype=float32)

In [21]:
pred = model.predict(X_train[2:3])

In [22]:
np.argmax(pred)

1