In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [3]:
note_seq[0:5], note_seq[1:6], note_seq[2:7]

(['g8', 'e8', 'e4', 'f8', 'd8'],
 ['e8', 'e4', 'f8', 'd8', 'd4'],
 ['e4', 'f8', 'd8', 'd4', 'c8'])

In [4]:
dataset = list()
for i in range(len(note_seq)-5):
  subset = note_seq[i:i+5]
  items = list()
  #print(subset)
  for item in subset:
    code2idx[item]
    #print(code2idx[item])
    items.append(code2idx[item])
  #print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9]]


In [5]:
import numpy as np
datasets = np.array(dataset)

In [7]:
x_train = datasets[:,0:4]
x_train.shape

(49, 4)

In [8]:
y_train = datasets[:,3]
y_train.shape

(49,)

In [9]:
len(code2idx)

14

In [10]:
x_train = x_train / 13 # len(code2idx)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308, 0.53846154])

# make model

In [11]:
import tensorflow as tf

In [12]:
x_train.shape, x_train[2]

((49, 4), array([0.15384615, 0.76923077, 0.61538462, 0.07692308]))

In [14]:
X_train = np.reshape(x_train,(49,4,1)) # tensor
X_train.shape, X_train[2]

((49, 4, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462],
        [0.07692308]]))

In [13]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(4,1))) #input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [15]:
hist = model.fit(X_train, y_train, epochs=1000, batch_size=10)

Epoch 1/1000
5/5 [==============================] - 2s 6ms/step - loss: 2.5463 - accuracy: 0.1020
Epoch 2/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.4857 - accuracy: 0.3265
Epoch 3/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.4339 - accuracy: 0.3265
Epoch 4/1000
5/5 [==============================] - 0s 7ms/step - loss: 2.3685 - accuracy: 0.3265
Epoch 5/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.2831 - accuracy: 0.3265
Epoch 6/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.1743 - accuracy: 0.3265
Epoch 7/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.0731 - accuracy: 0.3265
Epoch 8/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.0128 - accuracy: 0.3265
Epoch 9/1000
5/5 [==============================] - 0s 6ms/step - loss: 1.9798 - accuracy: 0.3265
Epoch 10/1000
5/5 [==============================] - 0s 7ms/step - loss: 1.9598 - accuracy: 0.3265
Epoch 11/1000
5/5 [

In [16]:
model.evaluate(X_train,y_train)

2/2 [==============================] - 0s 8ms/step - loss: 0.1457 - accuracy: 1.0000


[0.14574231207370758, 1.0]

In [22]:
X_train[2:3]

array([[[0.15384615],
        [0.76923077],
        [0.61538462],
        [0.07692308]]])

In [23]:
model.predict(X_train[2:3])

array([[2.0538260e-09, 9.9353361e-01, 2.4932176e-03, 1.8724420e-03,
        5.2515610e-05, 2.2466697e-09, 5.0653921e-09, 2.1289386e-09,
        2.0257665e-03, 2.2485090e-05, 2.1469940e-10, 1.0607232e-13,
        6.2965673e-09]], dtype=float32)

In [24]:
pred = model.predict(X_train[2:3])

In [25]:
np.argmax(pred)

1

In [ ]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']