In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [3]:
note_seq[0:5], note_seq[1:6], note_seq[2:7]

(['g8', 'e8', 'e4', 'f8', 'd8'],
 ['e8', 'e4', 'f8', 'd8', 'd4'],
 ['e4', 'f8', 'd8', 'd4', 'c8'])

In [4]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+5]
  items = list()
  #print(subset)
  for item in subset:
    code2idx[item]
    #print(code2idx[item])
    items.append(code2idx[item])
  #print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 8], [8, 1, 7, 8, 9], [1, 7, 8, 9, 10], [7, 8, 9, 10, 11], [8, 9, 10, 11, 11], [9, 10, 11, 11, 4], [10, 11, 11, 4, 11], [11, 11, 4, 11, 9], [11, 4, 11, 9, 9], [4, 11, 9, 9, 9], [11, 9, 9, 9, 10], [9, 9, 9, 10, 8], [9, 9, 10, 8, 1], [9, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2], [11, 9, 9, 2, 8], [9, 9, 2, 8, 8], [9, 2, 8, 8, 8], [2, 8, 8, 8, 8], [8, 8, 8, 8, 8], [8, 8, 8, 8, 9], [8, 8, 8, 9, 3], [8, 8, 9, 3, 9], [8, 9, 3, 9, 9], [9, 3, 9, 9, 9], [3, 9, 9, 9, 9], [9, 9, 9, 9, 9], [9, 9, 9, 9, 10], [9, 9, 9, 10, 4], [9, 9, 10, 4, 11], [9, 10, 4, 11, 9], [10, 4, 11, 9, 2], [4, 11, 9, 2, 10], [11, 9, 2, 10, 8], [9, 2, 10, 8, 1], [2, 10, 8, 1, 7], [10, 8, 1, 7, 9], [8, 1, 7, 9, 11], [1, 7, 9, 11, 11], [7, 9, 11, 11, 9], [9, 11, 11, 9, 9], [11, 11, 9, 9, 2]]


In [5]:
import numpy as np
datasets = np.array(dataset)

In [6]:
x_train = datasets[:,0:4]
x_train.shape

(50, 4)

In [7]:
y_train = datasets[:,3]
y_train.shape

(50,)

In [8]:
len(code2idx)

14

In [9]:
x_train = x_train / 14 # len(code2idx)
x_train[3]

array([0.71428571, 0.57142857, 0.07142857, 0.5       ])

# make model

In [10]:
import tensorflow as tf

In [11]:
x_train.shape, x_train[2]

((50, 4), array([0.14285714, 0.71428571, 0.57142857, 0.07142857]))

In [12]:
X_train = np.reshape(x_train,(50,4,1)) # tensor
X_train.shape, X_train[2]

((50, 4, 1), array([[0.14285714],
        [0.71428571],
        [0.57142857],
        [0.07142857]]))

In [13]:
model = tf.keras.models.Sequential()

model.add(tf.keras.Input(shape=(4,1))) #input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [14]:
hist = model.fit(X_train, y_train, epochs=1000, batch_size=10)

Epoch 1/1000
5/5 [==============================] - 1s 6ms/step - loss: 2.5551 - accuracy: 0.1200
Epoch 2/1000
5/5 [==============================] - 0s 5ms/step - loss: 2.5040 - accuracy: 0.3600
Epoch 3/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.4511 - accuracy: 0.3400
Epoch 4/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.3872 - accuracy: 0.3400
Epoch 5/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.3053 - accuracy: 0.3400
Epoch 6/1000
5/5 [==============================] - 0s 6ms/step - loss: 2.1970 - accuracy: 0.3400
Epoch 7/1000
5/5 [==============================] - 0s 7ms/step - loss: 2.0992 - accuracy: 0.3400
Epoch 8/1000
5/5 [==============================] - 0s 5ms/step - loss: 1.9855 - accuracy: 0.3400
Epoch 9/1000
5/5 [==============================] - 0s 9ms/step - loss: 1.9745 - accuracy: 0.3400
Epoch 10/1000
5/5 [==============================] - 0s 5ms/step - loss: 1.9556 - accuracy: 0.3400
Epoch 11/1000
5/5 [

In [15]:
model.evaluate(X_train,y_train)

2/2 [==============================] - 0s 7ms/step - loss: 0.1435 - accuracy: 0.9800


[0.14354710280895233, 0.9800000190734863]

In [16]:
X_train[2:3]

array([[[0.14285714],
        [0.71428571],
        [0.57142857],
        [0.07142857]]])

In [17]:
model.predict(X_train[2:3])

array([[1.1389888e-09, 9.9251819e-01, 2.0363042e-03, 1.5050923e-03,
        6.7695990e-05, 3.7773304e-10, 1.5802166e-09, 1.4136495e-09,
        3.8546419e-03, 1.8051445e-05, 1.3867585e-10, 3.5874336e-14,
        8.5249058e-10]], dtype=float32)

In [18]:
pred = model.predict(X_train[2:3])

In [19]:
np.argmax(pred)

1

In [20]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']