In [ ]:
import tensorflow as tf

In [ ]:
(x_train, y_train),(x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

In [ ]:
print(type(x_train))
print(type(x_train[0]), x_train[0])

In [ ]:
(x_train_100, y_train_100),(x_test_100, y_test_100) = tf.keras.datasets.imdb.load_data(num_words=100)
x_train_100.shape, y_train_100.shape, x_test_100.shape, y_test_100.shape

In [ ]:
print(type(x_train_100[0]), x_train_100[0])

<class 'list'> [1, 14, 22, 16, 43, 2, 2, 2, 2, 65, 2, 2, 66, 2, 4, 2, 36, 2, 5, 25, 2, 43, 2, 2, 50, 2, 2, 9, 35, 2, 2, 5, 2, 4, 2, 2, 2, 2, 2, 2, 39, 4, 2, 2, 2, 17, 2, 38, 13, 2, 4, 2, 50, 16, 6, 2, 2, 19, 14, 22, 4, 2, 2, 2, 4, 22, 71, 87, 12, 16, 43, 2, 38, 76, 15, 13, 2, 4, 22, 17, 2, 17, 12, 16, 2, 18, 2, 5, 62, 2, 12, 8, 2, 8, 2, 5, 4, 2, 2, 16, 2, 66, 2, 33, 4, 2, 12, 16, 38, 2, 5, 25, 2, 51, 36, 2, 48, 25, 2, 33, 6, 22, 12, 2, 28, 77, 52, 5, 14, 2, 16, 82, 2, 8, 4, 2, 2, 2, 15, 2, 4, 2, 7, 2, 5, 2, 36, 71, 43, 2, 2, 26, 2, 2, 46, 7, 4, 2, 2, 13, 2, 88, 4, 2, 15, 2, 98, 32, 2, 56, 26, 2, 6, 2, 2, 18, 4, 2, 22, 21, 2, 2, 26, 2, 5, 2, 30, 2, 18, 51, 36, 28, 2, 92, 25, 2, 4, 2, 65, 16, 38, 2, 88, 12, 16, 2, 5, 16, 2, 2, 2, 32, 15, 16, 2, 19, 2, 32]


In [ ]:
print(type(y_train[0]), y_train[0:5])

<class 'numpy.int64'> [1 0 0 1 0]


In [ ]:
import numpy as np

In [ ]:
np.unique(y_train)

array([0, 1])

In [ ]:
word_index = tf.keras.datasets.imdb.get_word_index()
print(type(word_index), word_index)

In [ ]:
word_index.items()

In [ ]:
invert_word_index = dict()
for (key,value) in word_index.items():
  invert_word_index[value] = key
print(invert_word_index)

In [ ]:
decode_str = str()
for num in x_train[0]:
  #print(i, invert_word_index[num])
  decode_str = decode_str + invert_word_index[num] + ' '

decode_str

In [ ]:
def f_decode_string(x_data):
  decode_str = str()
  for num in x_data:
    #print(i, invert_word_index[num])
    decode_str = decode_str + invert_word_index[num] + ' '

  return decode_str

In [ ]:
f_decode_string(x_train[20])

In [ ]:
f_decode_string(x_train_100[20])

# 데이터 전처리

In [ ]:
len(x_train[0]), len(x_train[50]), len(x_train[500]), len(x_train[1000])

(218, 113, 60, 298)

In [ ]:
sequence = [[1], 
            [2, 3], 
            [4, 5, 6]]
tf.keras.preprocessing.sequence.pad_sequences(sequence, maxlen=2, truncating='post')

array([[0, 1],
       [2, 3],
       [4, 5]], dtype=int32)

In [ ]:
pad_x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, maxlen=500)
len(pad_x_train[0]), pad_x_train[0]

(500, array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  

In [ ]:
np.unique(y_train) # --> Dense :1, activation:sigmoid, loss:binary_crossentropy

array([0, 1])

# make model

In [ ]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Embedding(input_dim=10000, output_dim=24, input_length=500)) # inputlayer
model.add(tf.keras.layers.LSTM(24, return_sequences=True, activation='tanh')) # hidden layer
model.add(tf.keras.layers.LSTM(12, activation='tanh')) # hidden layer
model.add(tf.keras.layers.Dense(1, activation='sigmoid')) # output layer

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc']) # gadget

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 24)           240000    
_________________________________________________________________
lstm (LSTM)                  (None, 500, 24)           4704      
_________________________________________________________________
lstm_1 (LSTM)                (None, 12)                1776      
_________________________________________________________________
dense (Dense)                (None, 1)                 13        
Total params: 246,493
Trainable params: 246,493
Non-trainable params: 0
_________________________________________________________________


In [22]:
hist = model.fit(pad_x_train, y_train, epochs=100, validation_split=0.3, batch_size= 256)

Epoch 1/100
69/69 [==============================] - 53s 711ms/step - loss: 0.6039 - acc: 0.6850 - val_loss: 0.4188 - val_acc: 0.8208
Epoch 2/100
69/69 [==============================] - 49s 708ms/step - loss: 0.3322 - acc: 0.8693 - val_loss: 0.3245 - val_acc: 0.8692
Epoch 3/100
69/69 [==============================] - 49s 707ms/step - loss: 0.2187 - acc: 0.9235 - val_loss: 0.3061 - val_acc: 0.8780
Epoch 4/100
69/69 [==============================] - 48s 702ms/step - loss: 0.1579 - acc: 0.9515 - val_loss: 0.3401 - val_acc: 0.8716
Epoch 5/100
69/69 [==============================] - 49s 707ms/step - loss: 0.1215 - acc: 0.9647 - val_loss: 0.3729 - val_acc: 0.8699
Epoch 6/100
69/69 [==============================] - 49s 708ms/step - loss: 0.1033 - acc: 0.9710 - val_loss: 0.4098 - val_acc: 0.8620
Epoch 7/100
69/69 [==============================] - 48s 701ms/step - loss: 0.0893 - acc: 0.9765 - val_loss: 0.4170 - val_acc: 0.8664
Epoch 8/100
69/69 [==============================] - 48s 699ms

# evaluation

In [23]:
model.evaluate(pad_x_train, y_train)

782/782 [==============================] - 48s 61ms/step - loss: 0.2895 - acc: 0.9561


[0.28949877619743347, 0.9561200141906738]

In [25]:
#len(x_test[20])
pad_x_test = tf.keras.preprocessing.sequence.pad_sequences(x_test, maxlen=500)
len(x_test[20]), len(pad_x_test[20])

(230, 500)

In [26]:
model.evaluate(pad_x_test)

782/782 [==============================] - 2s 2ms/step - loss: 0.0000e+00 - acc: 0.0000e+00


[0.0, 0.0]