In [1]:
import tensorflow as tf

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.reuters.load_data(num_words=10000)

x_train.shape, y_train.shape, x_test.shape, y_test.shape

2113536/2110848 [==============================] - 0s 0us/step


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/reuters.py:143: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/reuters.py:144: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


((8982,), (8982,), (2246,), (2246,))

In [3]:
print(type(x_train), type(x_train[0]))
print(x_train[3])
len(x_train[3])

<class 'numpy.ndarray'> <class 'list'>
[1, 4, 686, 867, 558, 4, 37, 38, 309, 2276, 465, 893, 3541, 114, 2902, 69, 312, 35, 15, 7, 335, 1679, 21, 25, 3675, 2, 3498, 58, 69, 68, 493, 5, 25, 465, 377, 2430, 4, 293, 1172, 739, 4379, 8, 7, 1510, 1131, 13, 899, 6, 4, 990, 309, 415, 4519, 6920, 645, 3916, 791, 5, 4379, 75, 8, 24, 10, 1311, 4677, 5, 344, 756, 7, 2, 231, 9691, 2603, 1413, 43, 509, 43, 68, 327, 5, 2, 3498, 297, 638, 73, 430, 22, 4, 580, 7, 48, 41, 30, 2, 136, 4, 344, 298, 4, 580, 40, 344, 5078, 2, 291, 1488, 10, 3148, 5, 231, 6250, 1308, 5, 8250, 7043, 21, 2, 1622, 990, 309, 415, 265, 5992, 8945, 1149, 9118, 2, 4, 344, 9691, 756, 3729, 2, 4667, 2, 3249, 28, 10, 2190, 24, 77, 41, 682, 10, 4851, 2048, 7, 4, 5540, 2926, 1598, 22, 370, 5954, 7541, 5, 54, 5232, 1685, 2916, 10, 1571, 946, 60, 51, 3249, 5249, 4, 73, 2135, 669, 4, 580, 64, 10, 4280, 6, 2, 25, 482, 35, 150, 377, 2430, 7, 10, 2, 836, 2, 4730, 6920, 5, 4379, 2, 2, 3541, 8, 4, 344, 291, 2, 298, 4228, 6, 2223, 24, 2, 41, 343

224

In [4]:
print(type(y_train), type(y_train[0]))
print(y_train[3])
print(y_train[0:5])

<class 'numpy.ndarray'> <class 'numpy.int64'>
4
[3 4 3 4 4]


In [5]:
import numpy as np

np.unique(y_train) # 장르 데이터

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
word_index = tf.keras.datasets.imdb.get_word_index()

1646592/1641221 [==============================] - 0s 0us/step


In [7]:
invert_word_index = dict()

for (key, value) in word_index.items():
  invert_word_index[value] = key

In [8]:
decode_str = str()

for num in x_train[0]:
  decode_str = decode_str + invert_word_index[num] + ' '  

decode_str

"the and and in out i several to have always place to catholic plot with women horror made can br don't to film characters is film does for made can great you lead he br what of good in believable or comedy work is old is first this for you 10 this for br what it christians ideas they're is although is different this for you while has this for with in between military made can very all comedy at an say is being for movie that "

# Data preprocessing

In [9]:
len(x_train[0]), len(x_train[50]), len(x_train[500]), len(x_train[1000])

(87, 118, 170, 626)

In [10]:
pad_x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, maxlen=500)
len(pad_x_train[0]), pad_x_train[0]

(500, array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  

In [11]:
np.unique(y_train)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

# Make model

In [12]:
model = tf.keras.models.Sequential()

# Input Layer
model.add(tf.keras.layers.Embedding(input_dim=10000, output_dim=24, input_length=500))

# Hidden Layer
model.add(tf.keras.layers.Flatten())

# Output Layer
model.add(tf.keras.layers.Dense(46, activation='softmax')) 


# Gadget
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) 


In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 24)           240000    
_________________________________________________________________
flatten (Flatten)            (None, 12000)             0         
_________________________________________________________________
dense (Dense)                (None, 46)                552046    
Total params: 792,046
Trainable params: 792,046
Non-trainable params: 0
_________________________________________________________________


In [14]:
hist = model.fit( pad_x_train, y_train, epochs=50, validation_split=0.3, batch_size=32 )

Epoch 1/50
197/197 [==============================] - 3s 14ms/step - loss: 2.1207 - accuracy: 0.4506 - val_loss: 1.6956 - val_accuracy: 0.5685
Epoch 2/50
197/197 [==============================] - 3s 13ms/step - loss: 1.3374 - accuracy: 0.6695 - val_loss: 1.3948 - val_accuracy: 0.6635
Epoch 3/50
197/197 [==============================] - 3s 13ms/step - loss: 0.7401 - accuracy: 0.8389 - val_loss: 1.2952 - val_accuracy: 0.6935
Epoch 4/50
197/197 [==============================] - 3s 13ms/step - loss: 0.4180 - accuracy: 0.9170 - val_loss: 1.2861 - val_accuracy: 0.7013
Epoch 5/50
197/197 [==============================] - 2s 12ms/step - loss: 0.2749 - accuracy: 0.9480 - val_loss: 1.3195 - val_accuracy: 0.7009
Epoch 6/50
197/197 [==============================] - 2s 12ms/step - loss: 0.2016 - accuracy: 0.9598 - val_loss: 1.3486 - val_accuracy: 0.7020
Epoch 7/50
197/197 [==============================] - 2s 12ms/step - loss: 0.1624 - accuracy: 0.9637 - val_loss: 1.3932 - val_accuracy: 0.6983

# Evaluation

In [15]:
model.evaluate(pad_x_train, y_train)

281/281 [==============================] - 1s 3ms/step - loss: 0.5002 - accuracy: 0.8948


[0.5002304315567017, 0.8947895765304565]

In [16]:
pad_x_test = tf.keras.preprocessing.sequence.pad_sequences(x_test, maxlen=500)
len(pad_x_test[20])

500

In [17]:
model.evaluate(pad_x_test)

71/71 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00


[0.0, 0.0]